version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  vleague-postgres:
    image: postgres:latest
    container_name: vleague-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  vleague-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: vleague-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
